services:
  exporter:
    image: prom/node-exporter
    command: --collector.disable-defaults --collector.textfile --collector.textfile.directory=/textfiles
    volumes:
      - ~/Library/Application Support/factorio/script-output/graftorio2/:/textfiles # macOS
    ports:
      - 9100:9100
